name: Run Unit Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  ruff:
    name: Run Ruff
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies for Ruff
      run: |
        python -m pip install --upgrade pip
        pip install ruff

    - name: Run Ruff Linting
      run: |
        ruff check src
        ruff check src --fix

  pylint:
    name: Run pylint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies for pylint
      run: |
        python -m pip install --upgrade pip
        pip install pylint

    - name: Run pylint with fail-under
      run: |
        pylint src --rcfile=.pylintrc --fail-under=10

  pytest:
    name: Run pytest
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install pytest dependencie
      run: |
        pip install pytest
        pip install pytest-cov

    - name: Set PYTHONPATH for the tests
      run: |
        echo "PYTHONPATH=$(pwd)/src" >> $GITHUB_ENV

    - name: Run unit test with pytest
      run: |
        pytest --cov=src/toxic_comment_classification_kedro tests/